---
kind: pipeline
name: Jira-Image
type: kubernetes
platform:
  os: linux
  arch: amd64
steps:
- name: build_push_to_ecr_prod
  image: plugins/ecr
  settings:
    access_key:
      from_secret: AWS_ACCESS_KEY_ID
    secret_key:
      from_secret: AWS_SECRET_ACCESS_KEY
    repo: dsa/jira
    registry: 340268328991.dkr.ecr.eu-west-2.amazonaws.com
    region: eu-west-2
    create_repository: false
    build_args:
    - APP_BUILD=${DRONE_COMMIT_SHA}
    - DOCKER_HOST=tcp://172.17.0.1:2375
    tags:
    - latest
    - ${DRONE_COMMIT_SHA}
  when:
    branch:
    - master
    event:
    - push

- name: build_push_to_ecr_dev
  image: plugins/ecr
  settings:
    access_key:
      from_secret: AWS_ACCESS_KEY_ID
    secret_key:
      from_secret: AWS_SECRET_ACCESS_KEY
    repo: dsa/jira
    registry: 340268328991.dkr.ecr.eu-west-2.amazonaws.com
    region: eu-west-2
    create_repository: false
    build_args:
    - APP_BUILD=${DRONE_COMMIT_SHA}
    - DOCKER_HOST=tcp://172.17.0.1:2375
    tags:
    - latest-dev
    - ${DRONE_COMMIT_SHA}
  when:
    branch:
    - development
    event:
    - push
