---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
- name: docker-build
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  # wait for docker service to be up before running docker build
  - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
  - docker build -t quay.io/ukhomeofficedigital/dsa-jira:$${DRONE_COMMIT_SHA} .
  environment:
#    DOCKER_HOST: tcp://172.17.0.1:2375
    DOCKER_PASSWORD:
      from_secret: docker_password
  when:
    event:
    - pull_request
    - push

    - name: docker-dev-push
      pull: if-not-exists
      image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
      commands:
    #   wait for docker service to be up before running docker build
      - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
      - docker login -u=$${DOCKER_USERNAME} -p=$${DOCKER_PASSWORD} quay.io
      - docker tag quay.io/ukhomeofficedigital/dsa-jira:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/dsa-jira:dev
      - docker push quay.io/ukhomeofficedigital/dsa-jira:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/dsa-jira:dev
      environment:
    #    DOCKER_HOST: tcp://172.17.0.1:2375
        DOCKER_USERNAME:
          from_secret: docker_username
        DOCKER_PASSWORD:
          from_secret: docker_password
      when:
        branch:
        - development
        event:
        - push

- name: docker-push
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
#   wait for docker service to be up before running docker build
  - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
  - docker login -u=$${DOCKER_USERNAME} -p=$${DOCKER_PASSWORD} quay.io
  - docker tag quay.io/ukhomeofficedigital/dsa-jira:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/dsa-jira:latest
  - docker push quay.io/ukhomeofficedigital/dsa-jira:$${DRONE_COMMIT_SHA}
  - docker push quay.io/ukhomeofficedigital/dsa-jira:latest
  environment:
#    DOCKER_HOST: tcp://172.17.0.1:2375
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  when:
    branch:
    - master
    event:
    - push

services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

...
